apps/adopcion/urls.py
from django.conf.urls import include, url

#bloquear acceso sabiendose la ruta sin estar logueado
from django.contrib.auth.decorators import login_required

from apps.adopcion.views import index_adopcion, SolicitudList, SolicitudCreate, SolicitudUpdate, SolicitudDelete


urlpatterns = [
    #url(r'^index$', index_adopcion),
    url(r'^listar/$', login_required(SolicitudList.as_view()), name ='solicitud_listar'),
    url(r'^nueva/$', login_required(SolicitudCreate.as_view()), name ='solicitud_crear'),
    url(r'^editar/(?P<pk>\d+)$', SolicitudUpdate.as_view(), name ='solicitud_editar'),
    url(r'^eliminar/(?P<pk>\d+)$', SolicitudDelete.as_view(), name ='solicitud_eliminar'),




]

apps/mascota/urls.py
from django.conf.urls import include, url
#bloquear acceso sabiendose la ruta sin estar logueado
from django.contrib.auth.decorators import login_required
from apps.mascota.views import listadoUsuarios, index, mascota_view, mascota_list, mascota_edit, \
								mascota_delete, MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete


urlpatterns = [
	url(r'^$', index, name = 'index'),
	# url de listar mascota con vista basada en clases
	url(r'^nuevo/$', login_required(MascotaCreate.as_view()), name = 'mascota_crear'),
	url(r'^listar/', login_required(MascotaList.as_view()), name = 'mascota_listar'),
	url(r'^editar/(?P<pk>\d+)/$', login_required(MascotaUpdate.as_view()), name = 'mascota_editar'),
  	url(r'^eliminar/(?P<pk>\d+)/$', login_required(MascotaDelete.as_view()), name = 'mascota_eliminar'),
  	url(r'^listado', listadoUsuarios, name = "listado"),

]

refugio/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^mascota/', include('apps.mascota.urls', namespace = 'mascota')),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace = 'adopcion')),
    url(r'^solicitud/', include('apps.adopcion.urls', namespace = 'solicitud')),
    url(r'^usuario/', include('apps.usuario.urls', namespace = 'usuario')),
    url(r'^accounts/login/',login, {'template_name':'index.html'}, name= 'login'),
    url(r'^logout/',logout_then_login, name= 'logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^reset/password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
    	
    #url(r'^$', include('apps.mascota.urls')),
]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{%block extrastatic %}
	{% endblock %}

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">

	<title>{% block title %}Refugio Animal {% endblock %}</title>
	
</head>
<body>

<div class="#">

	{% block navbar %}
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Logo</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mascota <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'mascota:mascota_crear' %}">Registrar</a></li>
							<li><a href="{% url 'mascota:mascota_listar' %}">Listar</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Adopción <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'adopcion:solicitud_crear' %}">Solicitar</a></li>
							<li><a href="{% url 'adopcion:solicitud_listar' %}">Listar</a></li>
						</ul>
					</li>
				</ul>
				
				<ul class="nav navbar-nav navbar-right">
					<li><a href="#">Centro canino CACHICHO</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Opciones <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'logout' %}">Salir</a></li>
						</ul>
					</li>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>
    {% endblock %}

    
	<!-- div que -->
    <div class="container">

		{% block header %}
		<h4>Listado de Maascotas</h4>
		{% endblock %}


		{% block content %}
		<h5>Este es el bloque del contenido del archivo base</h5>
		{% endblock %}


		
	</div>



</div>
	{% block extrajs %}
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	{% endblock %}

	
</body>
</html>